// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:efc6d0c0-ebc7-4e83-a412-83b7036d9531",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_tLE7kbPA0",
    "aws_user_pools_web_client_id": "24qlvdterjao6n28kpk3md6j6v",
    "aws_appsync_graphqlEndpoint": "https://sudjihk6sjb63i7eco4fhwr6ti.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
